In [1]:
import tensorflow as tf

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# # Q1 - Read the dataset

In [7]:
df = pd.read_csv ("C:\\Users\\hp\\Desktop\\Churn_Modelling.csv")

In [8]:
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
# Q2. Drop the columns which are unique for all users like IDs
# Q3. Distinguish the feature and target set

In [10]:
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [11]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [13]:
# x is the feature set and y is the target set.

In [14]:
# Encoding the Categorical Data

In [15]:
# Encoding Gender column

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])


In [17]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
# One hot coding Geography column

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [20]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [21]:
# Q4. Divide the data set into training and test sets

In [22]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [23]:
# Q5. Normalize the train and test data

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [25]:
# Q6. Initialize & build the model.

In [26]:
# Adding the input layer and the first hidden layer

In [27]:
from tensorflow.keras.models import Sequential

ann = Sequential()

In [28]:
from tensorflow.keras.layers import Dense
ann.add(Dense(units = 6, activation = 'relu'))

In [29]:
# Adding the second hidden layer

In [30]:
ann.add(Dense(units = 6, activation = 'relu'))

In [31]:
# Adding the output layer

In [32]:
ann.add(Dense(units = 1, activation = 'sigmoid'))

In [33]:
# Training the Model

In [34]:
ann.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [35]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 156us/sample - loss: 0.5375 - accuracy: 0.7855
Epoch 2/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.4679 - accuracy: 0.7959
Epoch 3/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.4466 - accuracy: 0.7977
Epoch 4/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4366 - accuracy: 0.8027
Epoch 5/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.4308 - accuracy: 0.8104
Epoch 6/100
8000/8000 [==============================] - 0s 60us/sample - loss: 0.4258 - accuracy: 0.8108
Epoch 7/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.4225 - accuracy: 0.8140
Epoch 8/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4194 - accuracy: 0.8155
Epoch 9/100
8000/8000 [==============================] - 0s 59us/sample - loss: 0.4168 - accuracy: 0.8202
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 0s 61us/sample - loss: 0.3338 - accuracy: 0.8635
Epoch 77/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.3334 - accuracy: 0.8629
Epoch 78/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.3335 - accuracy: 0.8630
Epoch 79/100
8000/8000 [==============================] - 0s 56us/sample - loss: 0.3336 - accuracy: 0.8625
Epoch 80/100
8000/8000 [==============================] - 0s 60us/sample - loss: 0.3333 - accuracy: 0.8636
Epoch 81/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3332 - accuracy: 0.8643
Epoch 82/100
8000/8000 [==============================] - 1s 76us/sample - loss: 0.3334 - accuracy: 0.8634
Epoch 83/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.3335 - accuracy: 0.8630
Epoch 84/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3332 - accuracy: 0.8636
Epoch 85/100
8000/8000 [==========================

In [36]:
# Q7. Predict the results

In [37]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis = 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [38]:
# Lets see how the model works. Given the below parameters, lets see how the model predicts.

# Geography - Germany

# Credit Score: 600

# Gender: Female

# Age: 50 years old

# Tenure: 1 years

# Balance: $ 6000

# Number of Products: 2

# Does this costumer have a credit card? Yes

# Is this costumer an Active Member?Yes

# Estimated Salary: $ 5000

In [39]:
ann.predict(sc.transform([[0, 0, 1, 600, 0, 50, 1, 6000, 2, 1, 1, 5000]]))

array([[0.14250125]], dtype=float32)

In [42]:
#As we see above, the outcome is in the form of probability, we change the above probability to the real output "1" or "0" by " > 0.5"! (as the threshold probability) 

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

In [43]:
# The model predicts that the customer will not churn and stay with the bank.

In [44]:
#Q8. Print the Accuracy score and confusion matrix

In [45]:
from sklearn.metrics import accuracy_score, confusion_matrix

cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print("Confusion Matrix")
print(cm)

print("The Accuracy Score of the model is")
print(ac)

Confusion Matrix
[[1523   72]
 [ 205  200]]
The Accuracy Score of the model is
0.8615
